// AUTO-GENERATED — do not edit manually.
// Generated from altair-attributes.csv on 2026-02-07
// 163 attributes total

export interface AltairAttribute {
  name: string;
  friendlyName: string;
  category: string;
  dataType: string;
  section: string;
  filterType: 'range' | 'flag' | 'choices';
  min?: number;
  max?: number;
  choices?: string[];
  isSelection: boolean;
  isOutput: boolean;
  isExtraCost: boolean;
}

export const ALTAIR_ATTRIBUTES: AltairAttribute[] = [
  {
    name: 'credit_score',
    friendlyName: 'Credit Score',
    category: 'General Credit Attributes',
    dataType: 'int',
    section: 'filter',
    filterType: 'range',
    min: 300,
    max: 900,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'addr_multi_unit',
    friendlyName: 'Multi-Unit Dwelling',
    category: 'Demographics / Property / Other',
    dataType: 'bit',
    section: 'filter',
    filterType: 'flag',
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'addr_pobox',
    friendlyName: 'PO Box',
    category: 'Demographics / Property / Other',
    dataType: 'bit',
    section: 'filter',
    filterType: 'flag',
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'age',
    friendlyName: 'Age',
    category: 'Demographics / Property / Other',
    dataType: 'tinyint',
    section: 'filter',
    filterType: 'range',
    min: 21,
    max: 99,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'hisp_surname',
    friendlyName: 'Hispanic Surname Indicator*',
    category: 'Demographics / Property / Other',
    dataType: 'bit',
    section: 'filter',
    filterType: 'flag',
    isSelection: true,
    isOutput: true,
    isExtraCost: true,
  },
  {
    name: 'income_est',
    friendlyName: 'Estimated Annual Income* (Values Are in 000\'s, Example 50 = 50,000)',
    category: 'Demographics / Property / Other',
    dataType: 'smallint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99999999,
    isSelection: true,
    isOutput: true,
    isExtraCost: true,
  },
  {
    name: 'mobilehomeind',
    friendlyName: 'Mobile/Manufactured Home',
    category: 'Demographics / Property / Other',
    dataType: 'bit',
    section: 'filter',
    filterType: 'flag',
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'va_confidence_rank',
    friendlyName: 'Presence of Veteran Likelihood*',
    category: 'Demographics / Property / Other',
    dataType: 'int',
    section: 'filter',
    filterType: 'choices',
    choices: ['1', '2', '3'],
    isSelection: true,
    isOutput: true,
    isExtraCost: true,
  },
  {
    name: 'vaflag',
    friendlyName: 'Presence of Veteran in Household*',
    category: 'Demographics / Property / Other',
    dataType: 'bit',
    section: 'filter',
    filterType: 'flag',
    isSelection: true,
    isOutput: true,
    isExtraCost: true,
  },
  {
    name: 'bk_flag_c13',
    friendlyName: 'Consumer Has Had a Chapter 13 Bankruptcy Ever (Limited Data)',
    category: 'Derogatory Credit Attributes',
    dataType: 'bit',
    section: 'derogatory',
    filterType: 'flag',
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'fc_flag',
    friendlyName: 'Consumer Has Ever Had a Real Estate Foreclosure',
    category: 'Derogatory Credit Attributes',
    dataType: 'tinyint',
    section: 'derogatory',
    filterType: 'flag',
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'gse_limit_eligible',
    friendlyName: 'Mortgage Loan Balance Is within the Conforming/GSE County Limit',
    category: 'Mortgage Attributes',
    dataType: 'tinyint',
    section: 'filter',
    filterType: 'flag',
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'reverse_mtg_flag',
    friendlyName: 'Reverse Mortgage Indicator*',
    category: 'Mortgage Attributes',
    dataType: 'int',
    section: 'filter',
    filterType: 'flag',
    isSelection: true,
    isOutput: true,
    isExtraCost: true,
  },
  {
    name: 'age_newest_auto_lease',
    friendlyName: 'Age in Months of Newest Open Auto Lease',
    category: 'Auto Attributes',
    dataType: 'smallint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 999,
    isSelection: false,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'age_newest_auto_loan',
    friendlyName: 'Age in Months of Newest Open Auto Loan',
    category: 'Auto Attributes',
    dataType: 'smallint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 999,
    isSelection: false,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'age_newest_auto_trd',
    friendlyName: 'Age in Months of Newest Opened Auto Trade (Loans and Leases)',
    category: 'Auto Attributes',
    dataType: 'smallint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 999,
    isSelection: false,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'age_oldest_auto_trd',
    friendlyName: 'Age In Months of Oldest Opened Auto Trade (Loans and Leases)',
    category: 'Auto Attributes',
    dataType: 'smallint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 999,
    isSelection: false,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'mon_pmt_oldest_open_auto_lease',
    friendlyName: 'Monthly Payment for Oldest Open Auto Lease',
    category: 'Auto Attributes',
    dataType: 'smallint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99999,
    isSelection: false,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'mon_pmt_oldest_open_auto_loan',
    friendlyName: 'Monthly Payment for Oldest Open Auto Loan',
    category: 'Auto Attributes',
    dataType: 'smallint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99999,
    isSelection: false,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'mon_pmt_oldest_open_auto_trd',
    friendlyName: 'Monthly Payment for the Oldest Open Auto Trade',
    category: 'Auto Attributes',
    dataType: 'smallint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99999,
    isSelection: false,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'num_open_auto_leases',
    friendlyName: 'Number of Open Auto Leases',
    category: 'Auto Attributes',
    dataType: 'smallint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99,
    isSelection: false,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'num_open_auto_loans',
    friendlyName: 'Number of Open Auto Loans',
    category: 'Auto Attributes',
    dataType: 'smallint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99,
    isSelection: false,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'num_open_auto_trds',
    friendlyName: 'Number of Open Auto Trades (Loans and Leases)',
    category: 'Auto Attributes',
    dataType: 'smallint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99,
    isSelection: false,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'ttl_bal_open_auto_leases',
    friendlyName: 'Total Current Balance for All Open Auto Leases',
    category: 'Auto Attributes',
    dataType: 'int',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99999999,
    isSelection: false,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'ttl_bal_open_auto_loans',
    friendlyName: 'Total Current Balance for All Open Auto Loans',
    category: 'Auto Attributes',
    dataType: 'int',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99999999,
    isSelection: false,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'ttl_bal_open_auto_trds',
    friendlyName: 'Total Current Balance of Open Auto Trades (Loans and Leases)',
    category: 'Auto Attributes',
    dataType: 'int',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99999999,
    isSelection: false,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'ttl_monthly_payment_open_auto_trds',
    friendlyName: 'Total Monthly Payment of All Open Auto Trades',
    category: 'Auto Attributes',
    dataType: 'int',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99999,
    isSelection: false,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'auto_bal',
    friendlyName: 'Current Balance for Most Recently Opened Auto Trade',
    category: 'Auto Trade Specific',
    dataType: 'bigint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99999999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'auto_est_apr',
    friendlyName: 'Estimated APR for Most Recently Opened Auto Trade',
    category: 'Auto Trade Specific',
    dataType: 'decimal',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'auto_high_credit',
    friendlyName: 'High Credit for Most Recently Opened Auto Trade',
    category: 'Auto Trade Specific',
    dataType: 'int',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99999999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'auto_mon_pmt',
    friendlyName: 'Monthly Payment for Most Recently Opened Auto Trade',
    category: 'Auto Trade Specific',
    dataType: 'int',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99999999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'auto_mons_remain',
    friendlyName: 'Number of Months Remaining for Most Recently Opened Auto Trade',
    category: 'Auto Trade Specific',
    dataType: 'smallint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'auto_mons_since',
    friendlyName: 'Number of Months Since Opened for Most Recently Opened Auto Trade',
    category: 'Auto Trade Specific',
    dataType: 'smallint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'auto_paid_thru',
    friendlyName: 'Paid Through Ratio (Balance/High Credit) for Most Recently Opened Auto Trade',
    category: 'Auto Trade Specific',
    dataType: 'tinyint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 100,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'auto_term',
    friendlyName: 'Term (Total Number of Payments) for Most Recently Opened Auto Trade',
    category: 'Auto Trade Specific',
    dataType: 'smallint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'auto_type',
    friendlyName: 'Type (Loan or Lease) for Most Recently Opened Auto Trade',
    category: 'Auto Trade Specific',
    dataType: 'char',
    section: 'filter',
    filterType: 'choices',
    choices: ['AL', 'AU'],
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'mons_since_recent_bk',
    friendlyName: 'Number of Months Since Most Recent Bankruptcy',
    category: 'Derogatory Credit Attributes',
    dataType: 'int',
    section: 'derogatory',
    filterType: 'range',
    min: 0,
    max: 999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'mons_since_recent_c13_bk',
    friendlyName: 'Number of Months Since Most Recent Ch 13 Bankruptcy (Limited Data)',
    category: 'Derogatory Credit Attributes',
    dataType: 'int',
    section: 'derogatory',
    filterType: 'range',
    min: 0,
    max: 999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'mons_since_recent_dc_c13_bk',
    friendlyName: 'Number of Months Since Most Recent Discharged Ch 13 Bankruptcy (Limited Data)',
    category: 'Derogatory Credit Attributes',
    dataType: 'int',
    section: 'derogatory',
    filterType: 'range',
    min: 0,
    max: 999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'mons_since_recent_dm_c13_bk',
    friendlyName: 'Number of Months Since Most Recent Dismissed Ch 13 Bankruptcy (Limited Data)',
    category: 'Derogatory Credit Attributes',
    dataType: 'int',
    section: 'derogatory',
    filterType: 'range',
    min: 0,
    max: 999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'mons_since_recent_fc',
    friendlyName: 'Number of Months Since Most Recent Foreclosure',
    category: 'Derogatory Credit Attributes',
    dataType: 'int',
    section: 'derogatory',
    filterType: 'range',
    min: 0,
    max: 999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'num_chg_off_trds',
    friendlyName: 'Number of Charged-Off Trades (Limited Data)',
    category: 'Derogatory Credit Attributes',
    dataType: 'tinyint',
    section: 'derogatory',
    filterType: 'range',
    min: 0,
    max: 99,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'num_mtg_trds_30dpd_12mons',
    friendlyName: 'Number of Mortgage Trades 30 Days Past Due in Past 12 Months',
    category: 'Derogatory Credit Attributes',
    dataType: 'smallint',
    section: 'derogatory',
    filterType: 'range',
    min: 0,
    max: 110,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'num_mtg_trds_60dpd_12mons',
    friendlyName: 'Number of Mortgage Trades 60 Days Past Due within 12 Months',
    category: 'Derogatory Credit Attributes',
    dataType: 'smallint',
    section: 'derogatory',
    filterType: 'range',
    min: 0,
    max: 110,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'num_mtg_trds_curr_60_to_180_dpd',
    friendlyName: 'Number of Mortgage Trades Presently 60 Days Past Due*',
    category: 'Derogatory Credit Attributes',
    dataType: 'int',
    section: 'derogatory',
    filterType: 'range',
    min: 0,
    max: 999,
    isSelection: true,
    isOutput: true,
    isExtraCost: true,
  },
  {
    name: 'num_mtg_trds_curr_90_to_180_dpd',
    friendlyName: 'Number of Mortgage Trades Presently 90 Days Past Due*',
    category: 'Derogatory Credit Attributes',
    dataType: 'int',
    section: 'derogatory',
    filterType: 'range',
    min: 0,
    max: 999,
    isSelection: true,
    isOutput: true,
    isExtraCost: true,
  },
  {
    name: 'num_trds_30_DPD_within_6mons',
    friendlyName: 'Number of Trades 30 Days Past Due within the Past 6 Months',
    category: 'Derogatory Credit Attributes',
    dataType: 'smallint',
    section: 'derogatory',
    filterType: 'range',
    min: 0,
    max: 99,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'num_trds_60_DPD_within_6mons',
    friendlyName: 'Number of Trades 60 Days Past Due within the Past 6 Months',
    category: 'Derogatory Credit Attributes',
    dataType: 'smallint',
    section: 'derogatory',
    filterType: 'range',
    min: 0,
    max: 99,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'dti_ratio',
    friendlyName: 'Debt to Income Ratio* (Enter 30=30%)',
    category: 'General Credit Attributes',
    dataType: 'int',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 100,
    isSelection: true,
    isOutput: true,
    isExtraCost: true,
  },
  {
    name: 'mon_pmt_rev_trds',
    friendlyName: 'Total Monthly Payment for Revolving Trades',
    category: 'General Credit Attributes',
    dataType: 'int',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'num_open_finance_trds',
    friendlyName: 'Number of Open Finance Trades',
    category: 'General Credit Attributes',
    dataType: 'smallint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'num_open_home_equity_trds',
    friendlyName: 'Number of Open Home Equity Trades',
    category: 'General Credit Attributes',
    dataType: 'smallint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'num_open_rev_trds',
    friendlyName: 'Number of Open Revolving Trades',
    category: 'General Credit Attributes',
    dataType: 'smallint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'num_open_trds',
    friendlyName: 'Number of Open Trades (All Trade Types)',
    category: 'General Credit Attributes',
    dataType: 'smallint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'num_sat_trds',
    friendlyName: 'Number of Satisfactory Trades',
    category: 'General Credit Attributes',
    dataType: 'smallint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'ttl_bal_open_install_trds',
    friendlyName: 'Total Balance of Open Installment Trades',
    category: 'General Credit Attributes',
    dataType: 'int',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99999999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'ttl_bal_open_rev_trds',
    friendlyName: 'Total Current Balance of Open Revolving Trades',
    category: 'General Credit Attributes',
    dataType: 'int',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99999999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'ttl_bal_open_rev_trds_no_heloc',
    friendlyName: 'Total Balance Open Revolving Trades Excluding HELOC',
    category: 'General Credit Attributes',
    dataType: 'int',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99999999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'ttl_bal_open_stuloan_trds',
    friendlyName: 'Total Balance of All Open Student Loan Trades',
    category: 'General Credit Attributes',
    dataType: 'int',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99999999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'ttl_bal_open_trds',
    friendlyName: 'Total Current Balance of Open Trades (All Trade Types)',
    category: 'General Credit Attributes',
    dataType: 'int',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99999999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'ttl_bal_open_trds_no_mtg_he',
    friendlyName: 'Total Balance of All Open Trades Excluding Mortgage and Home Equity Trades',
    category: 'General Credit Attributes',
    dataType: 'int',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99999999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'util_open_rev_trds_no_heloc',
    friendlyName: 'Utilization of Open Revolving Trades Excluding HELOC (Balance / Credit Limit, Example 50 = 50%)',
    category: 'General Credit Attributes',
    dataType: 'int',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'cltv',
    friendlyName: 'Loan-to-Value Based on Combined Mortgage and Home Equity Balances (CLTV)* (Example 50 = 50%)',
    category: 'Mortgage Attributes',
    dataType: 'int',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99999999,
    isSelection: true,
    isOutput: true,
    isExtraCost: true,
  },
  {
    name: 'conv_cashout_amt',
    friendlyName: 'Cash Out Amount - Conventional*',
    category: 'Mortgage Attributes',
    dataType: 'int',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99999999,
    isSelection: true,
    isOutput: true,
    isExtraCost: true,
  },
  {
    name: 'estimatedvalue',
    friendlyName: 'Estimated Home Value*',
    category: 'Mortgage Attributes',
    dataType: 'int',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99999999,
    isSelection: true,
    isOutput: true,
    isExtraCost: true,
  },
  {
    name: 'fha_mtg_curr_bal',
    friendlyName: 'Current Balance of Highest Balance FHA Mortgage',
    category: 'Mortgage Attributes',
    dataType: 'int',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99999999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'mtg_curr_bal',
    friendlyName: 'Current Balance of Mortgage',
    category: 'Mortgage Attributes',
    dataType: 'int',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99999999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'mtg_loan_type',
    friendlyName: 'Loan Type of Mortgage',
    category: 'Mortgage Attributes',
    dataType: 'varchar',
    section: 'filter',
    filterType: 'choices',
    choices: ['A', 'CONV', 'FHA', 'H', 'UNKNOWN', 'VA'],
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'mtg_mons_since_open',
    friendlyName: 'Number of Months Since Mortgage Was Opened',
    category: 'Mortgage Attributes',
    dataType: 'smallint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'mtg_orig_loan_amt',
    friendlyName: 'Original Loan Amount of Mortgage',
    category: 'Mortgage Attributes',
    dataType: 'int',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99999999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'mtg_rate',
    friendlyName: 'Estimated Mortgage Loan Interest Rate',
    category: 'Mortgage Attributes',
    dataType: 'numeric',
    section: 'filter',
    filterType: 'range',
    min: 1,
    max: 99,
    isSelection: true,
    isOutput: true,
    isExtraCost: true,
  },
  {
    name: 'newest_mtg_pmt',
    friendlyName: 'Monthly Payment for the Newest Mortgage Trade',
    category: 'Mortgage Attributes',
    dataType: 'int',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99999999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'num_open_heloan_trds',
    friendlyName: 'Number of Open Home Equity Loan Trades',
    category: 'Mortgage Attributes',
    dataType: 'smallint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 110,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'num_open_mtg_trds',
    friendlyName: 'Number of Open Mortgage Trades',
    category: 'Mortgage Attributes',
    dataType: 'smallint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 110,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'owner_status',
    friendlyName: 'Homeowner or Renter*',
    category: 'Mortgage Attributes',
    dataType: 'tinyint',
    section: 'filter',
    filterType: 'flag',
    isSelection: true,
    isOutput: true,
    isExtraCost: true,
  },
  {
    name: 'ttl_bal_open_heloan_trds',
    friendlyName: 'Total Balance of All Open Home Equity Loan Trades',
    category: 'Mortgage Attributes',
    dataType: 'int',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99999999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'ttl_bal_open_heloc_trds',
    friendlyName: 'Total Balance of All Open Home Equity Line of Credit Trades',
    category: 'Mortgage Attributes',
    dataType: 'int',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99999999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'ttl_bal_open_mtg_trds',
    friendlyName: 'Total Current Balance of All Open Mortgage Trades',
    category: 'Mortgage Attributes',
    dataType: 'int',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99999999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'ttl_mon_payment_open_mtg_trds',
    friendlyName: 'Total Monthly Payment for All Open Mortgage Trades',
    category: 'Mortgage Attributes',
    dataType: 'int',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99999999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'va_cashout_amt',
    friendlyName: 'Cash Out Amount - VA*',
    category: 'Mortgage Attributes',
    dataType: 'int',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99999999,
    isSelection: true,
    isOutput: true,
    isExtraCost: true,
  },
  {
    name: 'va_mtg_curr_bal',
    friendlyName: 'Current Balance of Highest Balance VA Mortgage',
    category: 'Mortgage Attributes',
    dataType: 'int',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99999999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'no_auto_trds_flag',
    friendlyName: 'No Open Auto Trades Flag',
    category: 'Auto Attributes',
    dataType: 'bit',
    section: 'filter',
    filterType: 'flag',
    isSelection: false,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'age_recent_closed_auto_trd',
    friendlyName: 'Age in Months of the Most Recent Closed Auto Trade',
    category: 'Auto Attributes',
    dataType: 'smallint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 999,
    isSelection: false,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'high_credit_open_auto_leases',
    friendlyName: 'High Credit Amount of All Open Auto Leases',
    category: 'Auto Attributes',
    dataType: 'int',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99999999,
    isSelection: false,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'high_credit_open_auto_loans',
    friendlyName: 'High Credit Amount of All Open Auto Loans',
    category: 'Auto Attributes',
    dataType: 'int',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99999999,
    isSelection: false,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'highest_apr_open_auto_loans',
    friendlyName: 'Highest Estimated APR for All Open Auto Loans',
    category: 'Auto Attributes',
    dataType: 'numeric',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 39,
    isSelection: false,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'highest_bal_open_auto_loans',
    friendlyName: 'Highest Current Balance for All Open Auto Loans',
    category: 'Auto Attributes',
    dataType: 'int',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99999999,
    isSelection: false,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'highest_bal_open_auto_trds',
    friendlyName: 'Highest Current Balance for All Open Auto Trades',
    category: 'Auto Attributes',
    dataType: 'int',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99999999,
    isSelection: false,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'mons_remain_oldest_open_auto_lease',
    friendlyName: 'Number of Months Remaining for Oldest Open Auto Lease',
    category: 'Auto Attributes',
    dataType: 'smallint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 999,
    isSelection: false,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'mons_remain_oldest_open_auto_loan',
    friendlyName: 'Number of Months Remaining for Oldest Open Auto Loan',
    category: 'Auto Attributes',
    dataType: 'smallint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 999,
    isSelection: false,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'mons_remain_oldest_open_auto_trd',
    friendlyName: 'Months Remaining for the Oldest open Auto Trade',
    category: 'Auto Attributes',
    dataType: 'smallint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 999,
    isSelection: false,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'num_auto_leases',
    friendlyName: 'Number of Auto Leases Ever',
    category: 'Auto Attributes',
    dataType: 'tinyint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 5,
    isSelection: false,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'num_auto_loans',
    friendlyName: 'Number of Auto Loans Ever',
    category: 'Auto Attributes',
    dataType: 'tinyint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 5,
    isSelection: false,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'ttl_high_credit_open_auto_trds',
    friendlyName: 'Aggregate High Credit (original loan amount) for All Open Auto Trades',
    category: 'Auto Attributes',
    dataType: 'int',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99999999,
    isSelection: false,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'ttl_paid_ratio_open_auto_leases',
    friendlyName: 'Total Paid Through Ratio (Balance/High Credit) for All Open Auto Leases',
    category: 'Auto Attributes',
    dataType: 'smallint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 199,
    isSelection: false,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'ttl_paid_ratio_open_auto_loans',
    friendlyName: 'Total Paid Through Ratio (Balance/High Credit) for All Open Auto Loans',
    category: 'Auto Attributes',
    dataType: 'smallint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 199,
    isSelection: false,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'lor',
    friendlyName: 'Length of Residence (in years)*',
    category: 'Demographics / Property / Other',
    dataType: 'tinyint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99,
    isSelection: true,
    isOutput: true,
    isExtraCost: true,
  },
  {
    name: 'ncoa_flag',
    friendlyName: 'Exclude Records that Have Moved to a New Address Determined by NCOA',
    category: 'Demographics / Property / Other',
    dataType: 'bit',
    section: 'filter',
    filterType: 'flag',
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'selfemployed',
    friendlyName: 'Household Includes Someone Who Is Self-Employed*',
    category: 'Demographics / Property / Other',
    dataType: 'bit',
    section: 'filter',
    filterType: 'flag',
    isSelection: true,
    isOutput: true,
    isExtraCost: true,
  },
  {
    name: 'bk_flag_60mons',
    friendlyName: 'Consumer Has Had a Bankruptcy Filed within the Past 5 Years',
    category: 'Derogatory Credit Attributes',
    dataType: 'bit',
    section: 'derogatory',
    filterType: 'flag',
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'bk_flag_72mons',
    friendlyName: 'Consumer Has Had a Bankruptcy Filed within the Past 6 Years',
    category: 'Derogatory Credit Attributes',
    dataType: 'bit',
    section: 'derogatory',
    filterType: 'flag',
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'bk_flag_84mons',
    friendlyName: 'Consumer Has Had a Bankruptcy Filed within the Past 7 Years',
    category: 'Derogatory Credit Attributes',
    dataType: 'bit',
    section: 'derogatory',
    filterType: 'flag',
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'num_trds_30dpd_ever',
    friendlyName: 'Number of Trades 30 or More Days Past Due Ever',
    category: 'Derogatory Credit Attributes',
    dataType: 'tinyint',
    section: 'derogatory',
    filterType: 'range',
    min: 0,
    max: 999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'num_trds_30_DPD_within_12mons',
    friendlyName: 'Number of Trades 30 Days Past Due within the Past 12 Months',
    category: 'Derogatory Credit Attributes',
    dataType: 'tinyint',
    section: 'derogatory',
    filterType: 'range',
    min: 0,
    max: 99,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'num_trds_30_DPD_within_24mons',
    friendlyName: 'Number of Trades 30 Days Past Due within the Past 24 Months',
    category: 'Derogatory Credit Attributes',
    dataType: 'tinyint',
    section: 'derogatory',
    filterType: 'range',
    min: 0,
    max: 99,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'num_trds_60_DPD_within_12mons',
    friendlyName: 'Number of Trades 60 Days Past Due within the Past 12 Months',
    category: 'Derogatory Credit Attributes',
    dataType: 'tinyint',
    section: 'derogatory',
    filterType: 'range',
    min: 0,
    max: 99,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'num_trds_60_DPD_within_24mons',
    friendlyName: 'Number of Trades 60 Days Past Due within the Past 24 Months',
    category: 'Derogatory Credit Attributes',
    dataType: 'tinyint',
    section: 'derogatory',
    filterType: 'range',
    min: 0,
    max: 99,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'num_trds_90_DPD_within_12mons',
    friendlyName: 'Number of Trades 90 Days Past Due within the Past 12 Months',
    category: 'Derogatory Credit Attributes',
    dataType: 'tinyint',
    section: 'derogatory',
    filterType: 'range',
    min: 0,
    max: 99,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'num_trds_90_DPD_within_24mons',
    friendlyName: 'Number of Trades 90 Days Past Due within the Past 24 Months',
    category: 'Derogatory Credit Attributes',
    dataType: 'tinyint',
    section: 'derogatory',
    filterType: 'range',
    min: 0,
    max: 99,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'num_times_30dpd_rev_trds_12mons',
    friendlyName: 'Number of Times 30 Days Past Due on Revolving Trades within the Last 12 Months (Limited Data)',
    category: 'Derogatory Credit Attributes',
    dataType: 'tinyint',
    section: 'derogatory',
    filterType: 'range',
    min: 0,
    max: 99,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'num_times_60dpd_rev_trds_12mons',
    friendlyName: 'Number of Times 60 Days Past Due on Revolving Trades within the Last 12 Months (Limited Data)',
    category: 'Derogatory Credit Attributes',
    dataType: 'tinyint',
    section: 'derogatory',
    filterType: 'range',
    min: 0,
    max: 99,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'age_newest_trd',
    friendlyName: 'Age in Months of Newest Opened Trade (All Trade Types)',
    category: 'General Credit Attributes',
    dataType: 'smallint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'age_oldest_trd',
    friendlyName: 'Age in Months of Oldest Opened Trade (All Trade Types)',
    category: 'General Credit Attributes',
    dataType: 'smallint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'age_newest_rev_trd',
    friendlyName: 'Age in Months of Newest Opened Revolving Trade',
    category: 'General Credit Attributes',
    dataType: 'smallint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'age_oldest_rev_trd',
    friendlyName: 'Age in Months of Oldest Opened Revolving Trade',
    category: 'General Credit Attributes',
    dataType: 'smallint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'age_newest_finance_trd',
    friendlyName: 'Age in Months of Newest Opened Finance Trade',
    category: 'General Credit Attributes',
    dataType: 'smallint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'age_newest_install_trd',
    friendlyName: 'Age in Months of Newest Opened Installment Trade',
    category: 'General Credit Attributes',
    dataType: 'smallint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'age_newest_stuloan_trd',
    friendlyName: 'Age in Months of Newest Opened Student Loan Trade',
    category: 'General Credit Attributes',
    dataType: 'smallint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'age_oldest_install_trd',
    friendlyName: 'Age in Months of Oldest Opened Installment Trade',
    category: 'General Credit Attributes',
    dataType: 'smallint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'age_oldest_stuloan_trd',
    friendlyName: 'Age in Months of Oldest Opened Student Loan Trade',
    category: 'General Credit Attributes',
    dataType: 'smallint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'age_newest_creditcard_trd',
    friendlyName: 'Age in Months of Newest Opened Credit Card Trade',
    category: 'General Credit Attributes',
    dataType: 'smallint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'age_oldest_creditcard_trd',
    friendlyName: 'Age in Months of Oldest Opened Credit Card Trade',
    category: 'General Credit Attributes',
    dataType: 'smallint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'high_credit_limit_open_rev_trds',
    friendlyName: 'Total Credit Limit for Open Revolving Trades (Available Credit Amount)',
    category: 'General Credit Attributes',
    dataType: 'int',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99999999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'high_credit_limit_open_creditcard_trds',
    friendlyName: 'Total Credit Limit for Open Credit Card Trades (Available Credit Amount)',
    category: 'General Credit Attributes',
    dataType: 'int',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99999999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'num_trds',
    friendlyName: 'Number of Trades',
    category: 'General Credit Attributes',
    dataType: 'smallint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'num_rev_trds',
    friendlyName: 'Number of Revolving Trades',
    category: 'General Credit Attributes',
    dataType: 'smallint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'num_deduped_inq',
    friendlyName: 'Number of Deduped Inquiries (All Trade Types)',
    category: 'General Credit Attributes',
    dataType: 'smallint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'num_install_trds',
    friendlyName: 'Number of Installment Trades',
    category: 'General Credit Attributes',
    dataType: 'smallint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'num_inq_within_3mons',
    friendlyName: 'Number of Inquiries within the Past 3 Months (All Trade Types)',
    category: 'General Credit Attributes',
    dataType: 'smallint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'num_inq_within_6mons',
    friendlyName: 'Number of Inquiries within the Past 6 Months (All Trade Types)',
    category: 'General Credit Attributes',
    dataType: 'smallint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'num_open_retail_trds',
    friendlyName: 'Number of Open Retail Trades',
    category: 'General Credit Attributes',
    dataType: 'smallint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'num_inq_within_12mons',
    friendlyName: 'Number of Inquiries within the Past 12 Months (All Trade Types)',
    category: 'General Credit Attributes',
    dataType: 'smallint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'num_open_install_trds',
    friendlyName: 'Number of Open Installment Trades',
    category: 'General Credit Attributes',
    dataType: 'smallint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'num_open_stuloan_trds',
    friendlyName: 'Number of Open Student Loan Trades',
    category: 'General Credit Attributes',
    dataType: 'smallint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'num_open_creditcard_trds',
    friendlyName: 'Number of Open Credit Card Trades',
    category: 'General Credit Attributes',
    dataType: 'smallint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'num_deferred_stuloan_trds',
    friendlyName: 'Number of Deferred Student Loan Trades',
    category: 'General Credit Attributes',
    dataType: 'smallint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'num_repayment_stuloan_trds',
    friendlyName: 'Number of Student Loan Trades in Repayment',
    category: 'General Credit Attributes',
    dataType: 'smallint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'num_deduped_inq_within_6mons',
    friendlyName: 'Number of Deduped Inquiries within the Past 6 Months (All Trade Types)',
    category: 'General Credit Attributes',
    dataType: 'smallint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'num_deduped_inq_within_12mons',
    friendlyName: 'Number of Deduped Inquiries within the Past 12 Months (All Trade Types)',
    category: 'General Credit Attributes',
    dataType: 'smallint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'num_open_repayment_stuloan_trds',
    friendlyName: 'Number of Open Student Loan Trades in Repayment',
    category: 'General Credit Attributes',
    dataType: 'smallint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'num_creditcard_trds_opened_24mons',
    friendlyName: 'Number of Credit Card Trades Opened within the Past 24 Months',
    category: 'General Credit Attributes',
    dataType: 'smallint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'ttl_bal_rev_trds',
    friendlyName: 'Total Current Balance of Revolving Trades',
    category: 'General Credit Attributes',
    dataType: 'int',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99999999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'ttl_bal_open_finance_trds',
    friendlyName: 'Total Balance Open Finance Trades',
    category: 'General Credit Attributes',
    dataType: 'int',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99999999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'ttl_bal_open_creditcard_trds',
    friendlyName: 'Total Balance of All Open Credit Card Trades',
    category: 'General Credit Attributes',
    dataType: 'int',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99999999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'ttl_bal_open_uns_install_trds',
    friendlyName: 'Total Balance of Open Unsecured Installment Trades (Limited Data)',
    category: 'General Credit Attributes',
    dataType: 'int',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99999999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'ttl_bal_open_rev_heloc_auto_trds',
    friendlyName: 'Total Combined Balance for Open Revolving, HELOC, and Auto Trades',
    category: 'General Credit Attributes',
    dataType: 'int',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99999999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'ttl_highcredit_open_uns_install_trds',
    friendlyName: 'Total Credit Line of Open Unsecured Installment Trades (Limited Data)',
    category: 'General Credit Attributes',
    dataType: 'int',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99999999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'ttl_bal_combined_rev_uns_install_trds',
    friendlyName: 'Total Balance of Combined Unsecured Debt',
    category: 'General Credit Attributes',
    dataType: 'int',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99999999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'ttl_credit_limit_open_home_equity_trds',
    friendlyName: 'Total Credit Limit Open Home Equity Trades',
    category: 'General Credit Attributes',
    dataType: 'int',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99999999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'util_open_trds',
    friendlyName: 'Utilization of Open Trades (Balance / Credit Limit, Example 50 = 50%)',
    category: 'General Credit Attributes',
    dataType: 'smallint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'util_open_rev_trds',
    friendlyName: 'Utilization of Revolving Trades (Balance / Credit Limit, Example 50 = 50%)',
    category: 'General Credit Attributes',
    dataType: 'smallint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99999999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'mons_since_recent_mtg_inq',
    friendlyName: 'Number of Months Since Most Recent Mortgage Inquiry',
    category: 'Mortgage Attributes',
    dataType: 'tinyint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'mons_since_recent_home_equity_trd',
    friendlyName: 'Number of Months Since Most Recent Home Equity Trade Was Opened',
    category: 'Mortgage Attributes',
    dataType: 'smallint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99999999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'num_mtg_trds',
    friendlyName: 'Number of Mortgages Ever',
    category: 'Mortgage Attributes',
    dataType: 'smallint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'num_open_heloc_trds',
    friendlyName: 'Number of Open Home Equity Line of Credit Trades',
    category: 'Mortgage Attributes',
    dataType: 'tinyint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 110,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'ttl_bal_open_home_equity_trds',
    friendlyName: 'Total Balance of Open Home Equity Trades',
    category: 'Mortgage Attributes',
    dataType: 'int',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99999999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'ttl_mon_payment_open_heloc_trds',
    friendlyName: 'Total Monthly Estimated Payment for Open HELOCs',
    category: 'Mortgage Attributes',
    dataType: 'int',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99999999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'ttl_mon_payment_open_heloan_trds',
    friendlyName: 'Total Monthly Estimated Payment for Open Home Equity Loans (Limited Data)',
    category: 'Mortgage Attributes',
    dataType: 'int',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99999999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'util_open_heloc_trds',
    friendlyName: 'Utilization of Open Home Equity Line of Credit Trades (Balance / Credit Limit, Example 50 = 50%)',
    category: 'General Credit Attributes',
    dataType: 'smallint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'util_open_trds_no_mtg_he',
    friendlyName: 'Utilization of Open Trades Excluding Mortgage and Home Equity (Balance / Credit Limit, Example 50 = 50%)',
    category: 'General Credit Attributes',
    dataType: 'smallint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'util_open_creditcard_trds',
    friendlyName: 'Utilization of Open Credit Card Trades (Balance / Credit Limit, Example 50 = 50%)',
    category: 'General Credit Attributes',
    dataType: 'smallint',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'ttl_bal_mtg_and_he',
    friendlyName: 'Combined Balance of All Open Mortgage and Home Equity Trades',
    category: 'Mortgage Attributes',
    dataType: 'int',
    section: 'filter',
    filterType: 'range',
    min: 0,
    max: 99999999,
    isSelection: true,
    isOutput: true,
    isExtraCost: false,
  },
  {
    name: 'bk_flag',
    friendlyName: 'Consumer Has Ever Had a Bankruptcy Filed',
    category: 'Derogatory Credit Attributes',
    dataType: 'bit',
    section: 'derogatory',
    filterType: 'flag',
    isSelection: true,
    isOutput: false,
    isExtraCost: false,
  }
];

export const ATTRIBUTE_MAP: Record<string, AltairAttribute> = Object.fromEntries(
  ALTAIR_ATTRIBUTES.map(a => [a.name, a])
);

export const ATTRIBUTES_BY_CATEGORY: Record<string, AltairAttribute[]> = {};
for (const a of ALTAIR_ATTRIBUTES) {
  if (!ATTRIBUTES_BY_CATEGORY[a.category]) ATTRIBUTES_BY_CATEGORY[a.category] = [];
  ATTRIBUTES_BY_CATEGORY[a.category].push(a);
}

export function getFriendlyName(attrName: string): string {
  return ATTRIBUTE_MAP[attrName]?.friendlyName || attrName.replace(/_/g, ' ');
}

export function formatAttributeValue(attrName: string, value: any): string {
  if (value === null || value === undefined) return '\u2014';
  const attr = ATTRIBUTE_MAP[attrName];
  if (!attr) return String(value);
  if (attr.filterType === 'flag') return value ? 'Yes' : 'No';
  if (attrName === 'income_est') return `$${Number(value).toLocaleString()}k`;
  if (attrName === 'dti_ratio' || attrName.startsWith('util_') || attrName === 'cltv' || attrName === 'auto_paid_thru') return `${value}%`;
  if (attrName === 'mtg_rate' || attrName === 'auto_est_apr') return `${value}%`;
  if (attrName.includes('_bal') || attrName.includes('_amt') || attrName === 'estimatedvalue' || attrName.includes('high_credit') || attrName.includes('mon_pmt') || attrName.includes('_pmt')) return `$${Number(value).toLocaleString()}`;
  return String(value);
}

// Category display order for UI
export const CATEGORY_ORDER = [
  'General Credit Attributes',
  'Mortgage Attributes',
  'Derogatory Credit Attributes',
  'Demographics / Property / Other',
  'Auto Attributes',
  'Auto Trade Specific',
];
