import { Professional, Review } from './types';

// Sarah Johnson's 10 highlighted reviews
const sarahJohnsonReviews: Review[] = [
  {
    id: 1,
    author: 'Michael & Jennifer Thompson',
    rating: 5,
    date: '2024-11-15',
    comment: 'Sarah made our first home buying experience absolutely seamless! She was patient, knowledgeable, and always available to answer our questions. We couldn\'t have asked for a better realtor.',
  },
  {
    id: 2,
    author: 'David Patterson',
    rating: 5,
    date: '2024-10-28',
    comment: 'Outstanding service from start to finish. Sarah\'s market knowledge helped us find the perfect home in Jonesboro within our budget. Her negotiation skills saved us over $15,000!',
  },
  {
    id: 3,
    author: 'Amanda & Chris Williams',
    rating: 5,
    date: '2024-10-12',
    comment: 'We relocated from out of state and Sarah went above and beyond to help us. She did video tours, coordinated with inspectors, and made the entire process stress-free. Highly recommend!',
  },
  {
    id: 4,
    author: 'Robert Garcia',
    rating: 5,
    date: '2024-09-30',
    comment: 'Sarah helped me sell my home in just 12 days above asking price! Her staging advice and marketing strategy were incredible. Already referred her to three friends.',
  },
  {
    id: 5,
    author: 'Lisa & Mark Anderson',
    rating: 5,
    date: '2024-09-18',
    comment: 'As first-time homebuyers, we were nervous about the process. Sarah took the time to explain everything and made sure we understood each step. She truly cares about her clients.',
  },
  {
    id: 6,
    author: 'Emily Chen',
    rating: 5,
    date: '2024-08-25',
    comment: 'Professional, responsive, and genuinely kind. Sarah helped my elderly parents downsize and handled everything with such care and patience. She\'s not just a realtor, she\'s family now!',
  },
  {
    id: 7,
    author: 'Jason & Brittany Moore',
    rating: 5,
    date: '2024-08-10',
    comment: 'This was our third time working with Sarah over the years. Each experience has been exceptional. She knows the Northeast Arkansas market like no one else.',
  },
  {
    id: 8,
    author: 'Stephanie Reynolds',
    rating: 5,
    date: '2024-07-22',
    comment: 'I was selling my late mother\'s home and Sarah handled the situation with such compassion and professionalism. She got us a great price and made a difficult time much easier.',
  },
  {
    id: 9,
    author: 'Kevin & Maria Santos',
    rating: 5,
    date: '2024-07-05',
    comment: 'Sarah found us our dream home after months of searching. She never gave up and always showed us properties that matched exactly what we were looking for. The best in the business!',
  },
  {
    id: 10,
    author: 'Daniel & Rachel Foster',
    rating: 5,
    date: '2024-06-18',
    comment: 'Five stars isn\'t enough for Sarah! She helped us navigate a complicated sale with multiple offers and made sure we came out on top. Her experience and expertise are unmatched.',
  },
];

export const mockProfessionals: Professional[] = [
  {
    id: 1,
    name: 'Sarah Johnson',
    company: 'Johnson Realty Group',
    category: 'Realtor',
    description: 'Experienced realtor specializing in first-time homebuyers and residential properties in Northeast Arkansas. Over 15 years helping families find their perfect home. Named "Top Realtor" by Arkansas Real Estate Magazine three years running. Known for her patient approach, market expertise, and dedication to finding the perfect home for every client.',
    photo: '/images/professionals/placeholder-1.jpg',
    serviceArea: ['Jonesboro', 'Brookland', 'Paragould', 'Bay', 'Trumann', 'Lake City'],
    phone: '(870) 555-0101',
    email: 'sarah@johnsonrealty.com',
    website: 'https://johnsonrealty.com',
    rating: 5.0,
    reviewCount: 500,
    yearsExperience: 15,
    isFeatured: true,
    city: 'Jonesboro',
    county: 'Craighead',
    reviews: sarahJohnsonReviews,
  },
  {
    id: 2,
    name: 'Mike Thompson',
    company: 'Arkansas Title Services',
    category: 'Title Company',
    description: 'Full-service title company providing title insurance, escrow services, and closing coordination for residential and commercial transactions.',
    photo: '/images/professionals/placeholder-2.jpg',
    serviceArea: ['Jonesboro', 'Little Rock', 'Conway'],
    phone: '(870) 555-0102',
    email: 'mike@artitleservices.com',
    website: 'https://artitleservices.com',
    rating: 4.8,
    reviewCount: 89,
    yearsExperience: 12,
    isFeatured: true,
    city: 'Jonesboro',
    county: 'Craighead',
  },
  {
    id: 3,
    name: 'David Chen',
    company: 'Premier Home Inspections',
    category: 'Home Inspector',
    description: 'Certified home inspector with expertise in structural, electrical, and plumbing systems. Detailed reports within 24 hours.',
    photo: '/images/professionals/placeholder-3.jpg',
    serviceArea: ['Jonesboro', 'Paragould', 'Trumann'],
    phone: '(870) 555-0103',
    email: 'david@premierhomeinspect.com',
    website: 'https://premierhomeinspect.com',
    rating: 5.0,
    reviewCount: 156,
    yearsExperience: 18,
    isFeatured: true,
    city: 'Jonesboro',
    county: 'Craighead',
  },
  {
    id: 4,
    name: 'Jennifer Williams',
    company: 'State Farm Insurance',
    category: 'Insurance Agent',
    description: 'Licensed insurance agent offering competitive rates on homeowners, auto, and life insurance. Free quotes and personalized service.',
    serviceArea: ['Jonesboro', 'Brookland'],
    phone: '(870) 555-0104',
    email: 'jennifer.williams@statefarm.com',
    rating: 4.7,
    reviewCount: 203,
    yearsExperience: 10,
    isFeatured: false,
    city: 'Jonesboro',
    county: 'Craighead',
  },
  {
    id: 5,
    name: 'Robert Martinez',
    company: 'Martinez Electric',
    category: 'Electrician',
    description: 'Licensed master electrician serving Northeast Arkansas. Residential and commercial electrical services, repairs, and upgrades.',
    serviceArea: ['Jonesboro', 'Paragould', 'Bay'],
    phone: '(870) 555-0105',
    email: 'robert@martinezelectric.com',
    website: 'https://martinezelectric.com',
    rating: 4.9,
    reviewCount: 78,
    yearsExperience: 22,
    isFeatured: false,
    city: 'Paragould',
    county: 'Craighead',
  },
  {
    id: 6,
    name: 'Lisa Anderson',
    company: 'Anderson Plumbing Co.',
    category: 'Plumber',
    description: 'Family-owned plumbing company with 24/7 emergency services. Specializing in repairs, installations, and water heater services.',
    serviceArea: ['Jonesboro', 'Brookland', 'Bono'],
    phone: '(870) 555-0106',
    email: 'lisa@andersonplumbing.com',
    rating: 4.6,
    reviewCount: 112,
    yearsExperience: 8,
    isFeatured: false,
    city: 'Jonesboro',
    county: 'Craighead',
  },
  {
    id: 7,
    name: 'James Wilson',
    company: 'Wilson General Contracting',
    category: 'General Contractor',
    description: 'Licensed general contractor for home renovations, additions, and new construction. Quality craftsmanship and on-time delivery.',
    photo: '/images/professionals/placeholder-4.jpg',
    serviceArea: ['Jonesboro', 'Paragould', 'Trumann', 'Bay'],
    phone: '(870) 555-0107',
    email: 'james@wilsongc.com',
    website: 'https://wilsongc.com',
    rating: 4.8,
    reviewCount: 94,
    yearsExperience: 25,
    isFeatured: true,
    city: 'Jonesboro',
    county: 'Craighead',
  },
  {
    id: 8,
    name: 'Amanda Brown',
    company: 'Brown Appraisal Services',
    category: 'Appraiser',
    description: 'Certified residential appraiser providing accurate and timely property valuations for purchases, refinances, and estates.',
    serviceArea: ['Jonesboro', 'Little Rock', 'Conway'],
    phone: '(870) 555-0108',
    email: 'amanda@brownappraisal.com',
    rating: 4.7,
    reviewCount: 67,
    yearsExperience: 14,
    isFeatured: false,
    city: 'Little Rock',
    county: 'Pulaski',
  },
  {
    id: 9,
    name: 'Tom Harris',
    company: 'Harris Handyman Services',
    category: 'Handyman',
    description: 'Experienced handyman for all your home repair needs. From minor fixes to major projects, no job is too small or too big.',
    serviceArea: ['Jonesboro', 'Brookland', 'Bono'],
    phone: '(870) 555-0109',
    email: 'tom@harrishandyman.com',
    rating: 4.5,
    reviewCount: 156,
    yearsExperience: 12,
    isFeatured: false,
    city: 'Jonesboro',
    county: 'Craighead',
  },
  {
    id: 10,
    name: 'Emily Davis',
    company: 'Davis HVAC Solutions',
    category: 'HVAC Technician',
    description: 'Licensed HVAC technician offering installation, repair, and maintenance services for all heating and cooling systems.',
    serviceArea: ['Jonesboro', 'Paragould', 'Trumann'],
    phone: '(870) 555-0110',
    email: 'emily@davishvac.com',
    website: 'https://davishvac.com',
    rating: 4.8,
    reviewCount: 89,
    yearsExperience: 9,
    isFeatured: false,
    city: 'Jonesboro',
    county: 'Craighead',
  },
  {
    id: 11,
    name: 'Chris Taylor',
    company: 'Taylor Roofing',
    category: 'Roofer',
    description: 'Full-service roofing company specializing in residential and commercial roof repair, replacement, and new installations.',
    photo: '/images/professionals/placeholder-5.jpg',
    serviceArea: ['Jonesboro', 'Paragould', 'Bay', 'Trumann'],
    phone: '(870) 555-0111',
    email: 'chris@taylorroofing.com',
    website: 'https://taylorroofing.com',
    rating: 4.9,
    reviewCount: 134,
    yearsExperience: 20,
    isFeatured: true,
    city: 'Jonesboro',
    county: 'Craighead',
  },
  {
    id: 12,
    name: 'Patricia Moore',
    company: 'Moore Realty',
    category: 'Realtor',
    description: 'Dedicated realtor helping buyers and sellers in the Little Rock metro area. Specializing in luxury homes and investment properties.',
    serviceArea: ['Little Rock', 'North Little Rock', 'Conway'],
    phone: '(501) 555-0112',
    email: 'patricia@moorerealty.com',
    website: 'https://moorerealty.com',
    rating: 4.6,
    reviewCount: 98,
    yearsExperience: 11,
    isFeatured: false,
    city: 'Little Rock',
    county: 'Pulaski',
  },
  {
    id: 13,
    name: 'Kevin White',
    company: 'White Pest Control',
    category: 'Pest Control',
    description: 'Professional pest control services for residential and commercial properties. Termite inspections and treatment specialists.',
    serviceArea: ['Jonesboro', 'Paragould', 'Brookland'],
    phone: '(870) 555-0113',
    email: 'kevin@whitepestcontrol.com',
    rating: 4.7,
    reviewCount: 76,
    yearsExperience: 15,
    isFeatured: false,
    city: 'Jonesboro',
    county: 'Craighead',
  },
  {
    id: 14,
    name: 'Maria Garcia',
    company: 'Sparkle Clean Services',
    category: 'Cleaning Service',
    description: 'Professional cleaning services for homes and offices. Move-in/move-out cleaning, deep cleaning, and regular maintenance.',
    serviceArea: ['Jonesboro', 'Brookland', 'Bono'],
    phone: '(870) 555-0114',
    email: 'maria@sparkleclean.com',
    rating: 4.8,
    reviewCount: 189,
    yearsExperience: 7,
    isFeatured: false,
    city: 'Jonesboro',
    county: 'Craighead',
  },
  {
    id: 15,
    name: 'Steve Jackson',
    company: 'Jackson Landscaping',
    category: 'Landscaper',
    description: 'Complete landscaping services including design, installation, and maintenance. Transform your outdoor space today.',
    photo: '/images/professionals/placeholder-6.jpg',
    serviceArea: ['Jonesboro', 'Paragould', 'Bay'],
    phone: '(870) 555-0115',
    email: 'steve@jacksonlandscaping.com',
    website: 'https://jacksonlandscaping.com',
    rating: 4.9,
    reviewCount: 112,
    yearsExperience: 16,
    isFeatured: false,
    city: 'Jonesboro',
    county: 'Craighead',
  },
  {
    id: 16,
    name: 'Nancy Clark',
    company: 'Fayetteville Title Group',
    category: 'Title Company',
    description: 'Trusted title company in Northwest Arkansas providing comprehensive title services and smooth closing experiences.',
    serviceArea: ['Fayetteville', 'Springdale', 'Rogers', 'Bentonville'],
    phone: '(479) 555-0116',
    email: 'nancy@fayettevilletitle.com',
    website: 'https://fayettevilletitle.com',
    rating: 4.8,
    reviewCount: 145,
    yearsExperience: 19,
    isFeatured: false,
    city: 'Fayetteville',
    county: 'Washington',
  },
  {
    id: 17,
    name: 'Daniel Lee',
    company: 'Lee Home Inspections',
    category: 'Home Inspector',
    description: 'Thorough home inspections with detailed reports. Serving Northwest Arkansas with professionalism and integrity.',
    serviceArea: ['Fayetteville', 'Springdale', 'Rogers'],
    phone: '(479) 555-0117',
    email: 'daniel@leeinspections.com',
    rating: 4.6,
    reviewCount: 87,
    yearsExperience: 10,
    isFeatured: false,
    city: 'Springdale',
    county: 'Washington',
  },
  {
    id: 18,
    name: 'Susan Wright',
    company: 'Wright Insurance Agency',
    category: 'Insurance Agent',
    description: 'Independent insurance agent offering the best rates from multiple carriers. Homeowners, auto, and umbrella policies.',
    serviceArea: ['Little Rock', 'Conway', 'North Little Rock'],
    phone: '(501) 555-0118',
    email: 'susan@wrightinsurance.com',
    website: 'https://wrightinsurance.com',
    rating: 4.9,
    reviewCount: 167,
    yearsExperience: 21,
    isFeatured: false,
    city: 'Conway',
    county: 'Faulkner',
  },
  {
    id: 19,
    name: 'Mark Robinson',
    company: 'Robinson Electric',
    category: 'Electrician',
    description: 'Reliable electrical services for homes and businesses. Panel upgrades, rewiring, and new construction.',
    serviceArea: ['Fort Smith', 'Van Buren'],
    phone: '(479) 555-0119',
    email: 'mark@robinsonelectric.com',
    rating: 4.7,
    reviewCount: 92,
    yearsExperience: 17,
    isFeatured: false,
    city: 'Fort Smith',
    county: 'Sebastian',
  },
  {
    id: 20,
    name: 'Laura King',
    company: 'King Property Appraisals',
    category: 'Appraiser',
    description: 'State-certified appraiser with extensive experience in residential properties throughout Central Arkansas.',
    serviceArea: ['Little Rock', 'North Little Rock', 'Sherwood', 'Jacksonville'],
    phone: '(501) 555-0120',
    email: 'laura@kingappraisals.com',
    rating: 4.8,
    reviewCount: 103,
    yearsExperience: 13,
    isFeatured: false,
    city: 'North Little Rock',
    county: 'Pulaski',
  },
];

export const getFeaturedProfessionals = (): Professional[] => {
  return mockProfessionals.filter(p => p.isFeatured);
};

export const getProfessionalsCount = (): number => {
  return mockProfessionals.length;
};
